function [out_data] = add_weighted_data(out_data, w1, data1)
    aux_count = zeros(size(out_data));
    for ss = 1:size(data1,2)
        for ff = 1:size(out_data,1)
            aux_count(   ff,...
                        data1(1,ss),...
                        data1(2,ss),...
                        data1(3,ss)) ...
            = ...
                        aux_count(   ff,...
                        data1(1,ss),...
                        data1(2,ss),...
                        data1(3,ss)) + 1;
                    
            out_data(   ff,...
                        data1(1,ss),...
                        data1(2,ss),...
                        data1(3,ss))...
            =... 
            out_data(   ff,...
                        data1(1,ss),...
                        data1(2,ss),...
                        data1(3,ss)) + w1 * data1(ff+3, ss);
        end
    end
    out_data = out_data./aux_count;
    out_data(isnan(out_data)) = 0;
end