function [X, Y, Z] = create_cartesian_grid(src_3d, ax_nsamples, az_nsamples, el_nsamples, type)
   
    [AXs, AZs, ELs] = create_polar_grid(src_3d,... 
                                        ax_nsamples,...
                                        az_nsamples,...
                                        el_nsamples,...
                                        type);

    [X, Y, Z] = polar_grid_to_cartesian_grid(src_3d, AXs, AZs, ELs);

end